version: '2'
services:
  web:
    build: .
    command: php -S 0.0.0.0:80 -t /code/web_site/
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - .:/code
  db:
    image: orchardup/mysql
    environment:
      MYSQL_DATABASE: web_db
